require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Starter' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'StarterTests' do
    inherit! :complete
    # Pods for testing
  end
  ENVFILES = {
    'Debug' => '$(PODS_ROOT)/../../.env',
    'Release' => '$(PODS_ROOT)/../../.env.prod',
  }
end

target 'Starter-tvOS' do
  # Pods for Starter-tvOS

  target 'Starter-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
